build_steps: &build_steps
  working_directory: ~/data_bus
  steps:
    - checkout
    - run: bundle install
    - run: bundle exec rake

version: 2
jobs:
  test_ruby-2.3:
    <<: *build_steps
    docker:
      - image: circleci/ruby:2.3
  test_ruby-2.4:
    <<: *build_steps
    docker:
      - image: circleci/ruby:2.4
  test_ruby-2.5:
    <<: *build_steps
    docker:
      - image: circleci/ruby:2.5

workflows:
  version: 2
  build:
    jobs:
      - test_ruby-2.3:
      - test_ruby-2.4:
      - test_ruby-2.5:
